# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.16.1, 1.16.0, 1.15.7, 1.14.5]
        otp: [26.2.2, 26.1.2, 26.0.2, 25.3.2.9, 24.3.4.16]


    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Elixir and Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-elixir-${{ matrix.elixir }}-otp-${{ matrix.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-elixir-${{ matrix.elixir }}-otp-${{ matrix.otp }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
